backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      #########################################
      #                                       #
      #              HOME PAGE                #
      #                                       #
      #########################################
      - file: "src/pages/index.md"
        label: "Home page"
        name: "index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Main Image,
              name: mainImage,
              widget: object,
              fields:
                [
                  { label: Description, name: description, widget: string },
                  {
                    label: Desktop,
                    name: desktop,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        {
                          label: X-position,
                          name: xPos,
                          widget: number,
                          default: 50,
                          valueType: "int",
                          min: 0,
                          max: 100,
                          step: 5,
                        },
                        {
                          label: Y-position,
                          name: yPos,
                          widget: number,
                          default: 50,
                          valueType: "int",
                          min: 0,
                          max: 100,
                          step: 5,
                        },
                      ],
                  },
                  {
                    label: Mobile,
                    name: mobile,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        {
                          label: X-position,
                          name: xPos,
                          widget: number,
                          default: 50,
                          valueType: "int",
                          min: 0,
                          max: 100,
                          step: 5,
                        },
                        {
                          label: Y-position,
                          name: yPos,
                          widget: number,
                          default: 50,
                          valueType: "int",
                          min: 0,
                          max: 100,
                          step: 5,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Introduction,
              name: introduction,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Text,
                    name: text,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
          - {
              label: CategoryPitch,
              name: categorypitch,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
      #########################################
      #                                       #
      #              HOME PAGE                #
      #                                       #
      #########################################
