backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      #########################################
      #                                       #
      #              HOME PAGE                #
      #                                       #
      #########################################
      - file: "src/pages/index.md"
        label: "Home page"
        name: "index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Main Image,
              name: mainImage,
              widget: object,
              fields:
                [
                  { label: Description, name: description, widget: string },
                  { label: Desktop, name: desktop, widget: image },
                  { label: Mobile, name: mobile, widget: image },
                ],
            }
      #########################################
      #                                       #
      #              HOME PAGE                #
      #                                       #
      #########################################
